version: "3.8"
services:
  app:
    ports:
      - 8000:8000
    image: katka05/mp:postgres
    command: sh -c './wait-for.sh http://db:5432 -- ./serverstart.sh'
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    deploy:
      placement:
        constraints:
          - node.role == manager

