version: "3.8"
services:
  app:
    ports:
      - 8000:8000
    image: katka05/mp:postgres
    command: ["./startserver.sh"]
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    deploy:
      placement:
        constraints:
          - node.role == manager
volumes:
  postgres_data
