version: '3.8'

services:
  django:
    image: katka05/mp:4
    ports:
      - "8000:8000"
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:latest
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'firewall'
      MYSQL_DATABASE: 'meetings'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'firewall'
