# Generated by Django 4.1.6 on 2023-09-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="duration",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="start_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
